---
- hosts: all
  tasks:
  - name: Refresh Apt Cache
    apt:
        update_cache: yes
  - name: Ensure needed packages installed
    package: name={{ item }}  state=present
    with_items:
        - vim
        - perl
        - rsync
        - man
        - build-essential
        - git
        - curl
        - wget
        - telnet
        - net-tools
  - name: configure /etc/hosts
    template:
      src: hosts.j2
      dest: /etc/hosts
  - name: Generate root ssh key
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_type: rsa
      ssh_key_file: /root/.ssh/id_rsa
    register: rootkey
  - name: place root pubkeys in authorized_keys
    authorized_key:
      key: "{{ hostvars[item].rootkey.ssh_public_key }}"
      state: present
      user: root
    with_items: "{{ groups['all'] }}"