# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
VAGRANT_VM_PROVIDER = "virtualbox"

Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
    VM_COUNT = 2

    config.vm.provider :virtualbox do | vb |
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
        vb.gui = true
    end
    
    (1..VM_COUNT).each do | machine_id |
        config.vm.define "level7cloud-base#{machine_id}" do | server |
            server.vm.hostname = "level7cloud-base#{machine_id}"
            server.vm.box = "debian/stretch64"
            server.vm.box_version = "9.5.0"
            server.vm.network :private_network, ip: "192.168.56.10#{machine_id}"
            server.vm.provider :virtualbox do | vb |
                vb.name = "level7cloud-base#{machine_id}"
            end

            # If this is the second machine, then run the ansible playbook

            if machine_id == VM_COUNT
                config.vm.provision "ansible" do | ansible |
                    ansible.playbook = 'playbook.yml'
                    ansible.become = true
                    ansible.limit = 'all'
                    ansible.groups = {
                        "group1" => ["level7cloud-base[1:2]"]
                    }
                end
            end
        end

        config.vm.provision "shell" do | s |
            s.inline = "apt install -y ansible"
        end
    end
end
