# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
VAGRANT_VM_PROVIDER = "virtualbox"

Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
    VM_COUNT = 2

    config.vm.provider :virtualbox do | vb |
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--natnet1", "10.3/16"]
        vb.gui = false
    end
    
    (1..VM_COUNT).each do | machine_id |
        config.vm.define "base-centos-#{machine_id}" do | server |
            server.vm.hostname = "base-centos-#{machine_id}"
            server.vm.box = "centos/7"
            server.vm.network :private_network, ip: "192.168.56.10#{machine_id}"
            server.vm.provider :virtualbox do | vb |
                vb.name = "base-centos-#{machine_id}"
            end

	    if machine_id == VM_COUNT
                server.vm.provision :ansible do |ansible|

                    # Disable default limit to connect to all the machines
                    ansible.limit = "all"
                    ansible.playbook = "playbook.yml"
		    ansible.become = true
                    ansible.groups = {
                        "group1" => ["base-centos-[1:#{machine_id}]"]
                    }
		end
            end
        end
    end
end
